apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    uid: prometheus-day13
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 5s
      prometheusType: Prometheus
      prometheusVersion: 3.13.1
